### PR TITLE
Add deterministic build script and update README

### PR DESCRIPTION
**Pull request by Varunram**
Before this, we were forced to do a couple of hacks each time we wanted to setup something on local. We now automate this and in the future must aim to remove this in favour of packages that work out of the box.

### CODE REVIEW

**Comment by Varunram** [comment]
NOTE: this contains @appa3151's PRs from the other branch, so merging this should automatically merge his changes in. @AliMeer please do make note of this in the commit log.

**Comment by AliMeer** [comment]
@Varunram is this the version that's building correctly?

**Comment by Varunram** [comment]
Yes, this was tested by Narayan as well.

**Comment by Varunram** [comment]
Base branch: https://github.com/thecryptobee/Hexa-Wallet/tree/HealthOfTheApp

**Pull request merged**
